name = "rat-mobile-ide"
compatibility_date = "2025-09-01"

# Pages Functions
pages_build_output_dir = ".solid/cloudflare"

[[kv_namespaces]]
binding = "SESSIONS"
id = "YOUR_SESSIONS_KV_NAMESPACE_ID"
preview_id = "YOUR_SESSIONS_KV_PREVIEW_ID"

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_CACHE_KV_NAMESPACE_ID" 
preview_id = "YOUR_CACHE_KV_PREVIEW_ID"

# Optional: Durable Object for real-time features
# [[durable_objects.bindings]]
# name = "RUNS"
# class_name = "RunsDurableObject"
# script_name = "rat-mobile-ide"

[vars]
GITHUB_CLIENT_ID = "${GITHUB_CLIENT_ID}"
GITHUB_CLIENT_SECRET = "${GITHUB_CLIENT_SECRET}"
APP_BASE_URL = "https://rat-ide.pages.dev"
AI_AGENT_URL = "${AI_AGENT_URL}"
AI_AGENT_KEY = "${AI_AGENT_KEY}"

# Placement for optimal performance
[placement]
mode = "smart"

# Development environment variables
[env.development.vars]
APP_BASE_URL = "http://localhost:8788"
DEBUG = "true"

# Production environment variables  
[env.production.vars]
APP_BASE_URL = "https://ide.yourdomain.com"
DEBUG = "false"